apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app2
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flask-app2
  template:
    metadata:
      labels:
        app: flask-app2
    spec:
      containers:
      - name: flask-app2
        image: 940482417779.dkr.ecr.us-east-1.amazonaws.com/flask-app2
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "250m"
            memory: "256Mi"
